[package]
name    = "fibonacci"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fibonacci"
path = "src/main.rs"

[dependencies]

[profile.release]
opt-level = "s"
lto       = true
panic     = "abort"
